version: "3"
services:
  pg_primary:
    build: ./primary
    container_name: pg_primary
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=db
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=123456
    networks:
      default:
        aliases:
          - pg_cluster
  pg_replica_1:
    build: ./replica
    container_name: pg_replica_1
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=db
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=123456
      - PG_MASTER_HOST=pg_primary
    networks:
      default:
        aliases:
          - pg_cluster
  pg_replica_2:
    build: ./replica
    container_name: pg_replica_2
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=db
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=123456
      - PG_MASTER_HOST=pg_primary
    networks:
      default:
        aliases:
          - pg_cluster
volumes:
  pg_data: